import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className={inter.className}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Explore, Share and discover</h1>
        <h1>Your gateway to authentic travel experience</h1>
        <h3 className={styles.description}>Lorem ipsum Lorem lorem lorem lorem lorem</h3>
      </main>
    </div>
  )
}
